### PR TITLE
Fix bindAll usage

### PR DESCRIPTION
**Pull request by Khamurdik**
_.bindAll is mutable function and doesn't return any value. Variable obj is mutated and must be returned after _.bindAll call.

### CODE REVIEW

**Comment by robaleman** [comment]
Thank you!

**Comment by dakebl** [comment]
@joshkatz this fixed the issue. Can you please merge this in?

**Comment by Sifogiannos** [comment]
Does not seem to be merged, i dislike hardcoding this kind on thing in node_modules, what should we do?

**Comment by Khamurdik** [comment]
You can get module directly from my GitHub by writing in your 'package.json':
  "dependencies": {
    "r-script": "git+https://git@github.com/khamurdik/r-script.git"
  }

**Comment by Sifogiannos** [comment]
Thanks for your quick response, this approach is a bit more elegant, i would preffer a better solution through npm but i cannot as too much. I hope you do not delete the repository.

**Comment by djpalumbo** [comment]
@joshkatz Are there any plans to publish this patch through NPM?

**Comment by JosephGJ** [comment]
@joshkatz I would also like to see this patch published through NPM

**Pull request merged**
