### PR TITLE
Fix for issue 'unexpected end of input' error in call function by JSON.parse

### PR DESCRIPTION
**Pull request by payousefi**
Referenced in issue #5

### CODE REVIEW

**Comment by patrickcze** [comment]
This is an important bug fix that should be accepted as it resolves an issue with async calls

**Comment by andru** [comment]
Async is very broken without this fix. I'm currently using payousefi's fork in production code. @joshkatz please merge this.

**Comment by andru** [comment]
🙌🏼

**Comment by ccornchip** [comment]
Unfortunately, this causes an a fatal error when R encounters an exception:

body === "" as nothing is in stdout (it all goes to stderr)
then when the callback child.on('close', ...) is called, it causes an 'unexpected end of input' error in function by JSON.parse

I think this can be fixed by https://github.com/joshkatz/r-script/pull/7

**Pull request merged**
